// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsmwktmxrwoxnnddosxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzbXdrdG14cndveG5uZGRvc3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODEwNzQsImV4cCI6MjA2NDQ1NzA3NH0.xI1M3iqtSAkESLtgKXaE5fyurfb340IyQfvcGovmBQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);